name: ${project.artifactId}
version: ${project.version}

main: de.bloodeko.towns.Towns
api-version: 1.13

softdepend: [WorldEdit, WorldGuard, Vault]

commands:
  stadt:
    description: Town commands.
    usage: /<command>
  gs:
    description: Plot commands.
    usage: /<command>