name: ${project.artifactId}
version: ${project.version}

main: de.bloodeko.towns.Towns
api-version: 1.13

softdepend: [WorldEdit, WorldGuard]

commands:
  town:
    description: Bundles town commands.
    usage: /<command>
